- hosts: "{{ hosts }}"
  gather_facts: no

  pre_tasks:
  - name: Create folders
    win_file:
      path: "{{ item }}"
      state: directory
    with_items:
    - "{{ tools_path }}"
    - "{{ tools_path }}\\diag"
    - "{{ dump_path }}"
    - "{{ symbols_path }}"
  - name: Install Chocolatey packages
    win_chocolatey:
      name: "{{ item }}"
      state: latest
    with_items: "{{ choco_apps }}"
  - import_tasks: locate-debugging-tools.yml

  roles:
  - err
  - sysinternals
  - process-hacker
  - debugging-tools
  - performance-toolkit
  - dnspy
  - perfview
  - wtrace
  - powershell
  #- touchcursor

  post_tasks:
  - name: Adding additional folders to PATH variable
    win_path:
      state: present
      scope: machine
      elements: [ 
                  "{{ tools_path }}\\diag",  
                  "%SYSTEMROOT%\\Microsoft.NET\\Framework64\\v4.0.30319"
                ]
  - name: Disable GAC view in Windows Explorer
    win_regedit: 
      path: HKLM:\Software\Microsoft\Fusion
      name: DisableCacheViewer
      type: dword
      data: 1
