---
- name: Make sure tools path exists
  win_file:
    path: "{{ tools_path }}\\diag"
    state: directory
- name: Download PerfView
  win_get_url:
    url: https://github.com/Microsoft/perfview/releases/download/P2.0.7/{{ item }}
    dest: "{{ tools_path }}\\diag\\{{ item }}"
  loop: [ PerfView.exe, PerfView.pdb, PerfView64.exe, PerfView64.pdb ]
- name: Updating PATH variable
  win_path:
    state: present
    scope: machine
    elements: "{{ tools_path }}\\diag"
