---
- name: Make sure tools path exists
  win_file:
    path: "{{ tools_path }}"
    state: directory
- name: Make sure dump folder exists
  win_file:
    path: "{{ dump_path }}"
    state: directory
- name: Download Sysinternals Suite
  win_get_url:
    url: https://download.sysinternals.com/files/SysinternalsSuite.zip
    dest: "{{ tools_path }}"
- name: Download Sysinternals Suite for Nano Server
  win_get_url:
    url: https://download.sysinternals.com/files/SysinternalsSuite-Nano.zip
    dest: "{{ tools_path }}"
- name: Unzip binaries
  win_unzip:
    delete_archive: yes
    src: "{{ tools_path }}\\{{ item }}"
    dest: "{{ tools_path }}\\sysinternals"
  with_items: [ SysinternalsSuite.zip, SysinternalsSuite-Nano.zip ]
- name: Agree to EULA
  win_regedit:
    path: HKCU:\Software\Sysinternals\{{ item }}
    name: EulaAccepted
    type: dword
    data: 1
  with_items:
    - AccessChk
    - AutoRuns
    - DbgView
    - Junction
    - LiveKd
    - LogonSessions
    - PendMove
    - ProcDump
    - Process Explorer
    - Process Monitor
    - PsExec
    - PsList
    - PsLoggedon
    - PsLoglist
    - PsPing
    - PsService
    - SDelete
    - sigcheck
    - Strings
    - TCPView
    - VMMap
    - Whois
    - Winobj
    - ZoomIt
- name: Prepare external symbols folder
  win_file: 
    path: "{{ symbols_path }}\\dbg"
    state: directory
- name: Prepare private symbols folder
  win_file:
    path: "{{ symbols_path }}\\private"
    state: directory
- name: Configure dbghelp path in Process Monitor
  win_regedit:
    path: HKCU:\Software\Sysinternals\Process Monitor
    name: DbgHelpPath
    type: string
    data: "{{ dbgtools_path }}\\dbghelp.dll"
  when: dbgtools_path != ''
- name: Configure symbols path in Process Monitor
  win_regedit:
    path: HKCU:\Software\Sysinternals\Process Monitor
    name: SymbolPath
    type: string
    data: "{{ symbols_path}}\\private;SRV*{{ symbols_path }}\\dbg*https://msdl.microsoft.com/download/symbols"
- name: Configure dbghelp path in Process Explorer
  win_regedit:
    path: HKCU:\Software\Sysinternals\Process Explorer
    name: DbgHelpPath
    type: string
    data: "{{ dbgtools_path }}\\dbghelp.dll"
  when: dbgtools_path != ''
- name: Configure symbols path in Process Monitor
  win_regedit:
    path: HKCU:\Software\Sysinternals\Process Explorer
    name: SymbolPath
    type: string
    data: "{{ symbols_path}}\\private;SRV*{{ symbols_path }}\\dbg*https://msdl.microsoft.com/download/symbols"
- name: Add sysinternals to PATH
  win_path:
    state: present
    scope: machine
    elements: "{{ tools_path }}\\sysinternals"
#- name: Run ZoomIt on start
#  win_regedit:
#    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Run
#    name: ZoomIt
#    type: string
#    data: "{{ tools_path }}\\sysinternals\\ZoomIt.exe"
- name: Configure ProcDump as system debugger (AeDebug)
  win_shell: "& \"{{ tools_path }}\\sysinternals\\procdump.exe\" -i \"{{ dump_path }}\" -mp"
  register: procdump_res
  ignore_errors: yes # FIXME: sometimes fails - to diagnose
- debug:
    msg: "{{ procdump_res.stdout }}"
- name: Replace Task Explorer with Process Explrer
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\taskmgr.exe
    name: Debugger
    type: string
    data: "\"{{ tools_path }}\\sysinternals\\procexp.exe\""
- name: Replace Task Explorer with Process Explorer (x86)
  win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\taskmgr.exe
    name: Debugger
    type: string
    data: "\"{{ tools_path }}\\sysinternals\\procexp.exe\""
