---
- name: Make sure tools path exists
  win_file:
    path: "{{ tools_path }}\\diag"
    state: directory
- name: Download Process Hacker binaries
  win_get_url:
    url: https://wj32.org/processhacker/rel/processhacker-2.39-bin.zip
    dest: "{{ tools_path }}\\diag"
- name: Unzip binaries
  win_unzip:
    delete_archive: yes
    src: "{{ tools_path }}\\diag\\processhacker-2.39-bin.zip"
    dest: "{{ tools_path }}\\diag\\processhacker"
- name: Process Hacker appdata folder
  win_file:
    path: "%APPDATA%\\Process Hacker 2"
    state: directory
- name: Process Hacker configuration files
  win_template:
    src: "{{ item }}"
    dest: "%APPDATA%\\Process Hacker 2\\{{ item | replace('.j2', '') }}"
  with_items: [ usernotesdb.xml.j2, settings.xml.j2 ]
  when: dbgtools_path != ''
- name: Prepare external symbols folder
  win_file: 
    path: "{{ symbols_path }}\\dbg"
    state: directory
- name: Set _NT_SYMBOL_PATH
  win_environment:
    state: present
    name: _NT_SYMBOL_PATH
    level: machine
    value: "SRV*{{ symbols_path }}\\dbg*https://msdl.microsoft.com/download/symbols"
- name: Replace Task Explorer with Process Hacker
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\taskmgr.exe
    name: Debugger
    type: string
    data: "\"{{ tools_path }}\\diag\\processhacker\\x64\\ProcessHacker.exe\""
- name: Replace Task Explorer with Process Hacker (x86)
  win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\taskmgr.exe
    name: Debugger
    type: string
    data: "\"{{ tools_path }}\\diag\\processhacker\\x64\\ProcessHacker.exe\""
